// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huhthdmdettqfkhaulro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aHRoZG1kZXR0cWZraGF1bHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjI1NTksImV4cCI6MjA3MzY5ODU1OX0.6OdAbfmLk1f5KoQAcF6L7xsPS4kyKTjJy8v1C1uVQ1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});